#!/bin/bash

for OS in linux darwin windows
do
    export GOOS=$OS
    export GOARCH="386"
    export FILENAME="dsc-flutter-installer"

    # Building 32-bit executables in MacOS is not allowed anymore
    if [ $OS = "darwin" ]; then
        GOARCH="amd64"
        FILENAME="$FILENAME-macos"
    else
        FILENAME="$FILENAME-$GOOS"
    fi

    if [ $OS = "windows" ]; then
        FILENAME="$FILENAME.exe"
    fi

    echo go build -o bin/$FILENAME .
    go build -o bin/$FILENAME .
done