#!/bin/bash

for ARCH in x86 arm64
do
    for OS in linux macos windows
    do
        export GOOS=$OS
        export GOARCH=$ARCH
        export ARCHLABEL=$ARCH

        if [ $ARCH = "x86" ]; then
            GOARCH="386"
        fi

        # Building 32-bit executables in MacOS is not allowed anymore
        if [ $OS = "macos" ]; then
            if [ $ARCH = "x86" ]; then
                GOARCH="amd64"
                ARCHLABEL="x86_64"
            fi

            # Label arm64 as apple_silicon in MacOS for easy recognition
            if [ $ARCH = "arm64" ]; then
                ARCHLABEL="apple_silicon"
            fi

            GOOS="darwin"
        fi

        export FILENAME="flutter-installer_$OS-$ARCHLABEL"

        if [ $OS = "windows" ]; then
            FILENAME="$FILENAME.exe"
        fi

        echo go build -o bin/$FILENAME .
        go build -o bin/$FILENAME .
    done
done